"""empty message

Revision ID: 7ddc9f38f470
Revises: 
Create Date: 2024-11-06 15:56:47.032453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddc9f38f470'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.create_index('idx_property_status', ['property_id', 'status'], unique=False)
        batch_op.create_index('idx_tour_time', ['tour_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_index('idx_tour_time')
        batch_op.drop_index('idx_property_status')

    # ### end Alembic commands ###
