"""empty message

Revision ID: dff72179a26a
Revises: 7ddc9f38f470
Create Date: 2024-11-06 16:00:33.285189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff72179a26a'
down_revision = '7ddc9f38f470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
